quantity_of_men = int(10)
pi_number = float(3.14)
status = bool(False)
poem = str("something")
the_first_number = int(2)
str_rivers = poem[::-1]
powerfull_item = "Blade"
next_day = "Saturday"
day_of_victory = 9
last_5elements = poem[-5:]
type_of_variable = type(pi_number)
week = "Monday " + "Other days"
growth = bool(1.80)
speed_limit = int(120)
day_off = "Sunday"
side_of_tringle1 = float(20)
perimetr = side_of_tringle1 + side_of_tringle1 + gipot
statement = True
month_4 = "April"
step_1 = "left"
